# https://github.com/golangci/golangci-lint#config-file
version: '1.61.0'
run:
  concurrency: 8
  timeout: 120s
  tests: false
linters: # Descriptions: https://github.com/golangci/awesome-go-linters
  # To see those enabled by default `golangci-lint help linters`
  enable: # These are disabled by default by golangci-lint
    - dogsled
    - gochecknoinits
    - goconst
    - errcheck
    - goimports
    - revive
    - gosec
    - rowserrcheck
    - stylecheck
    - unparam
